services:
  db:
    image: postgres:16
    env_file:
      - .env
    environment:
      POSTGRES_DB: ${DATABASE_NAME}
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"   # opcional, remova se não for acessar pelo host

  django-web:
    build: .
    container_name: django-docker
    depends_on:
      - db
    env_file:
      - .env
    ports:
      - "8000:8000"
    # Django só precisa das variáveis via env_file

volumes:
  postgres_data:
