# Generated by Django 5.2.6 on 2025-12-09 23:28

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Events', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='eventos',
            name='categoria',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='eventos', to='Events.categoria'),
        ),
        migrations.AddField(
            model_name='eventos',
            name='categoria_secundaria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='eventos_secundarios', to='Events.categoria'),
        ),
        migrations.AddField(
            model_name='eventos',
            name='data_criacao',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='eventos',
            name='faixa_etaria',
            field=models.CharField(choices=[('LIVRE', 'Livre'), ('MAIOR_12', 'Maior de 12 anos'), ('MAIOR_16', 'Maior de 16 anos'), ('MAIOR_18', 'Maior de 18 anos'), ('MAIOR_21', 'Maior de 21 anos')], default='LIVRE', max_length=20),
        ),
        migrations.AddField(
            model_name='eventos',
            name='horário',
            field=models.TimeField(default='12:00'),
        ),
        migrations.AddField(
            model_name='eventos',
            name='situacao',
            field=models.CharField(choices=[('NAO_INICIADO', 'Não Iniciado'), ('EM_ANDAMENTO', 'Em Andamento'), ('CONCLUIDO', 'Concluído'), ('CANCELADO', 'Cancelado')], default='NAO_INICIADO', max_length=20),
        ),
        migrations.AddField(
            model_name='local',
            name='capacidade',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='local',
            name='endereco',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='local',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='local',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='local',
            name='nome',
            field=models.CharField(default='sem nome', max_length=150),
        ),
        migrations.AddField(
            model_name='local',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='locais', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='categoria',
            name='id_categoria',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='categoria',
            name='nome',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='eventos',
            name='data',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='eventos',
            name='local',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eventos', to='Events.local'),
        ),
        migrations.AlterField(
            model_name='eventos',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eventos', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id_reserva', models.AutoField(primary_key=True, serialize=False)),
                ('preco', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('status', models.CharField(choices=[('PENDENTE', 'Pendente'), ('CONFIRMADA', 'Confirmada'), ('CANCELADA', 'Cancelada'), ('FINALIZADA', 'Finalizada')], default='PENDENTE', max_length=20)),
                ('data_reserva', models.DateTimeField(auto_now_add=True)),
                ('quantidade_ingressos', models.IntegerField(default=1)),
                ('evento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservas', to='Events.eventos')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservas', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
