# Generated by Django 5.2.6 on 2025-12-09 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Events', '0003_eventos_categoria_eventos_categoria_secundaria_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoria',
            name='id_categoria',
            field=models.IntegerField(default=0, primary_key=True, serialize=False),
        ),
    ]
