# Generated by Django 5.2.6 on 2025-12-09 23:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Events', '0005_alter_categoria_id_categoria_alter_eventos_categoria'),
    ]

    operations = [
        migrations.RenameField(
            model_name='eventos',
            old_name='horário',
            new_name='horario',
        ),
    ]
