# Generated by Django 5.2.7 on 2025-12-12 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Events', '0006_rename_horário_eventos_horario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventos',
            name='categoria',
        ),
        migrations.RemoveField(
            model_name='eventos',
            name='categoria_secundaria',
        ),
        migrations.RemoveField(
            model_name='eventos',
            name='horario',
        ),
        migrations.AddField(
            model_name='eventos',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='eventos_fotos/'),
        ),
        migrations.AddField(
            model_name='eventos',
            name='tags',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='eventos',
            name='tipo',
            field=models.CharField(choices=[('Presencial', 'Presencial'), ('Online', 'Online'), ('Híbrido', 'Híbrido')], default='Presencial', max_length=20),
        ),
        migrations.AlterField(
            model_name='eventos',
            name='data',
            field=models.DateTimeField(),
        ),
    ]
