# Generated by Django 5.2.8 on 2025-11-06 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Events', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventos',
            name='data',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
