# Generated by Django 5.2.7 on 2025-11-10 19:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Events', '0003_local_capacidade_local_endereco_local_latitude_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='reserva',
            name='data_reserva',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='eventos',
            name='descricao',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='eventos',
            name='local',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='local_eventos', to='Events.local'),
        ),
        migrations.AlterField(
            model_name='eventos',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usuario_eventos', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='local',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='usuario_local', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='id_reserva',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='status',
            field=models.CharField(default='pendente', max_length=50),
        ),
    ]
