# Generated by Django 5.2.7 on 2025-10-27 23:40

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Events', '0003_local_capacidade_local_endereco_local_latitude_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserva',
            name='data_reserva',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
