# Generated by Django 5.2.7 on 2025-11-07 00:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pessoafisica',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='pessoajuridica',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='segurancamoderacao',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='usuario',
            options={'ordering': ['id']},
        ),
    ]
