# Generated by Django 5.2.8 on 2025-11-06 00:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FAQ', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notificacao',
            old_name='conteudo',
            new_name='mensagem',
        ),
        migrations.RenameField(
            model_name='pergunta',
            old_name='txt',
            new_name='texto',
        ),
        migrations.RenameField(
            model_name='resposta',
            old_name='txt',
            new_name='texto',
        ),
    ]
