# Generated by Django 5.2.6 on 2025-11-07 01:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FAQ', '0004_voto_data_alter_voto_pergunta_voto_voto_unico'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notificacao',
            options={'ordering': ['-data']},
        ),
    ]
